version: 2
jobs:
  test-api:
    docker:
    - image: openjdk:alpine

    working_directory: ~/repo

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "api/build.gradle" }}
        - v1-dependencies-
    - run: ./gradlew dependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "api/build.gradle" }}
    - run: ./gradlew test

  test-web:
    docker:
    - image: circleci/node

    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "web/package.json" }}
        - v1-dependencies-

    - run: cd web && yarn install
    - save_cache:
        paths:
        - web/node_modules
        key: v1-dependencies-{{ checksum "web/package.json" }}
    - run: cd web && yarn test

  build-api:
    docker:
    - image: openjdk:alpine

    working_directory: ~/repo

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "api/build.gradle" }}
        - v1-dependencies-
    - run: ./gradlew dependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "api/build.gradle" }}
    - run: ./gradlew assemble
    - run: mkdir -p /tmp/workspace/api
    - run: mv api/build/libs/ /tmp/workspace/api
    - persist_to_workspace:
        root: /tmp/workspace
        paths:
        - api


  build-web:
    docker:
    - image: circleci/node

    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "web/package.json" }}
        - v1-dependencies-

    - run: cd web && yarn install
    - save_cache:
        paths:
        - web/node_modules
        key: v1-dependencies-{{ checksum "web/package.json" }}
    - run: cd web && yarn build
    - run: mkdir -p /tmp/workspace/web
    - run: mv web/build /tmp/workspace/web
    - persist_to_workspace:
        root: /tmp/workspace
        paths:
        - web

  deploy:
    docker:
    - image: governmentpaas/cf-cli

    working_directory: ~/repo

    steps:
    - checkout
    - attach_workspace:
        at: /tmp/workspace
    - run: ls /tmp/workspace

workflows:
  version: 2
  build_and_test:
    jobs:
    - test-api
    - test-web

    - build-api:
        requires:
        - test-api
        - test-web

    - build-web:
        requires:
        - test-api
        - test-web

    - deploy:
        requires:
        - build-api
        - build-web